// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Persimmon.Unquote")>]
[<assembly: AssemblyProductAttribute("Persimmon.Unquote")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Persimmon.Unquote"
    let [<Literal>] AssemblyProduct = "Persimmon.Unquote"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
    let [<Literal>] AssemblyInformationalVersion = "0.2.0"
